alternatif/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
]

perhitungan/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name="index"),
    path('hapus/<str:kode>', views.hapus, name="hapus" ),
    path('edit/<str:kode>', views.edit, name="edit" ),
]

spk1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('alternatif/',include(('alternatif.urls', 'alternatif'), namespace="alternatif")),
    path('perhitungan/',include(('perhitungan.urls', 'perhitungan'), namespace="perhitungan")),

]

alternatif/models.py
from django.db import models
class alternatif(models.Model):
    kodealternatif = models.CharField(max_length=3, primary_key=True)
    namaalternatif = models.CharField(max_length=25)
    c1 = models.FloatField()
    c2 = models.FloatField()
    angka= (
        (1, 'KURANG MENDUKUNG'),
        (2, 'CUKUP MENDUKUNG'),
        (3, 'SANGAT MENDUKUNG'),
    )
    c3 = models.FloatField(choices=angka, default=1)
    prio = (
        (1, 'SANGAT PRIORITAS'),
        (2, 'PRIORITAS'),
        (3, 'KURANG PRIORITAS'),
    )
    c4 = models.FloatField(choices=prio, default=1)
    oleh = (
        (1, 'SULIT DIPEROLEH'),
        (2, 'SEDIKIT MUDAH DIPEROLEH'),
        (3, 'SANGAT MUDAH DIPEROLEH'),
    )
    c5 = models.FloatField(choices=oleh, default=1)

    def __str__(self):
        return "{}". format(self.kodealternatif)
class normalisasi(models.Model):
    kodealternatif = models.CharField(max_length=3)
    c1norm = models.IntegerField()
    c2norm = models.IntegerField()
    c3norm = models.IntegerField()
    c4norm = models.IntegerField()
    c5norm = models.IntegerField()
    def __str__(self):
        return "{}". format(self.kodealternatif)

kriteria/models.py
from django.db import models

# Create your models here.

perhitungan/models.py
from django.db import models

# Create your models here.

alternatif/views.py
from django.shortcuts import render, redirect
from .table import formtabel
from django.db.models import Max, Min, F
from .models import alternatif, normalisasi
def index(request):
    form_input = formtabel(request.POST or None)
    if form_input.is_valid():
        form_input.save()
        return redirect('alternatif:index')
    context = {
        'title':'ALTERNATIF',
        'table':form_input,
        'tombol':'Tambahkan'
    }
    return render(request, 'alternatif/index.html', context)

kriteria/views.py
from django.shortcuts import render

# Create your views here.

perhitungan/views.py
from django.shortcuts import render, redirect
from django.db.models import Max, Min, F
from alternatif.models import alternatif, normalisasi
from alternatif.table import formtabel
def index(request):
    form_input = alternatif.objects.all()
    minc1 = alternatif.objects.aggregate(Min('c1')).get('c1__min')
    minc4 = alternatif.objects.aggregate(Min('c4')).get('c4__min')
    maxc2 = alternatif.objects.aggregate(Max('c2')).get('c2__max')
    maxc3 = alternatif.objects.aggregate(Max('c3')).get('c3__max')
    maxc5 = alternatif.objects.aggregate(Max('c5')).get('c5__max')
    c1norm = alternatif.objects.values_list(F('c1')/minc1, flat=True)
    c2norm = alternatif.objects.values_list(F('c2')/maxc2, flat=True)
    c3norm = alternatif.objects.values_list(F('c3')/maxc3, flat=True)
    c4norm = alternatif.objects.values_list(F('c4')/minc4, flat=True)
    c5norm = alternatif.objects.values_list(F('c5')/maxc5, flat=True)

    c1normbobot = alternatif.objects.values_list(F('c1')/minc1*0.25, flat=True)
    c2normbobot = alternatif.objects.values_list(F('c2')/maxc2*0.15, flat=True)
    c3normbobot = alternatif.objects.values_list(F('c3')/maxc3*0.30, flat=True)
    c4normbobot = alternatif.objects.values_list(F('c4')/minc4*0.25, flat=True)
    c5normbobot = alternatif.objects.values_list(F('c5')/maxc5*0.05, flat=True)

    result = alternatif.objects.all().annotate(prod=F('c1')/minc1*0.25 + 
    F('c2')/maxc2*0.15 + F('c3')/maxc3*0.30 + F('c4')/minc4*0.25 + F('c5')/maxc5*0.05)

    result2 = alternatif.objects.all().values_list(F('c1')/minc1*0.25 + 
    F('c2')/maxc2*0.15 + F('c3')/maxc3*0.30 + F('c4')/minc4*0.25 + F('c5')/maxc5*0.05)
   
    context = {
        'title':'PERHITUNGAN',
        'table':form_input,
        'normc1':c1norm,
        'normc2':c2norm,
        'normc3':c3norm,
        'normc4':c4norm,
        'normc5':c5norm,
        'botc1':c1normbobot,
        'botc2':c2normbobot,
        'botc3':c3normbobot,
        'botc4':c4normbobot,
        'botc5':c5normbobot,
        'hasil':result,
        'hasil2':result2,
    }
    return render(request, 'perhitungan/index.html', context)
def hapus(request, kode):
    tables = alternatif.objects.filter(kodealternatif=kode).delete()
    return redirect('perhitungan:index')
def edit(request, kode):
    editakun = alternatif.objects.get(kodealternatif=kode)
    data={
        'kodealternatif':editakun.kodealternatif,
        'namaalternatif':editakun.namaalternatif,
        'c1':editakun.c1,
        'c2':editakun.c2,
        'c3':editakun.c3,
        'c4':editakun.c4,
        'c5':editakun.c5,
    }
    form_input = formtabel(request.POST or None, initial=data, instance=editakun)
    if request.method == "POST":
        if form_input.is_valid():
            form_input.save()
            return redirect('perhitungan:index')
    context={
        'title':'AKUN|UPDATE',
        'table':form_input,
        'tombol':'Edit',
    }
    return render(request, 'alternatif/index.html', context)

spk1/views.py
from django.shortcuts import render
def index(request):
    context = {
        'title':'SPK',
    }
    return render(request, 'index.html', context)
# Create your views here.

alternatif/templates/alternatif/index.html
{% extends "dasar.html" %}
{% block satu %}
<div class="container">
<form method="POST">
{% csrf_token %}
    <table>
        <div class="form-row">
            <div class="form-group col-md-2">
            <label>{{table.kodealternatif.label}}</label>
            {{table.kodealternatif}}
            </div>
        </div>
        <div class ="form-row">
            <div class = "form-group col-md-6">
            <label>{{table.namaalternatif.label}}</label>
            {{table.namaalternatif}}
            </div>
        </div>
        <div class = "form-row">
            <div class="form-group col-md-4">
            <label>{{table.c1.label}}</label>
            {{table.c1}}
            </div>
        </div>
        <div class = "form-row">
            <div class="form-group col-md-4">
            <label>{{table.c2.label}}</label>
            {{table.c2}}
            </div>
        </div>
        <div class = "form-row">
            <div class="form-group col-md-4">
            <label>{{table.c3.label}}</label>
            {{table.c3}}
            </div>
        </div>
        <div class = "form-row">
            <div class="form-group col-md-4">
            <label>{{table.c4.label}}</label>
            {{table.c4}}
            </div>
        </div>
        <div class = "form-row">
            <div class="form-group col-md-4">
            <label>{{table.c5.label}}</label>
            {{table.c5}}
            </div>
        </div>
    </table>
<button type="submit" class="btn btn-primary">{{tombol}}</button>
</form>

</div>

{% endblock satu %}

perhitungan/templates/perhitungan/index.html
{% extends "dasar.html" %}
{% block satu %}
<div class="main" style="margin-left: 20px;">
<h4>TABEL ALTERNATIF</h4>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">KODE ALTERNATIF</th>
      <th scope="col">NAMA ALTERNATIF</th>
      <th scope="col">C1</th>
      <th scope="col">C2</th>
      <th scope="col">C3</th>
      <th scope="col">C4</th>
      <th scope="col">C5</th>
      <th scope="col">ACTION</th>
    </tr>
  </thead>
  <tbody>
    {% for a in table %}
    <tr>
      <td>{{a.kodealternatif}}</td>
      <td>{{a.namaalternatif}}</td>
      <td>{{a.c1}}</td>
      <td>{{a.c2}}</td>
      <td>{{a.c3}}</td>
      <td>{{a.c4}}</td>
      <td>{{a.c5}}</td>
      <td><a href="{% url "perhitungan:hapus" a.kodealternatif %}" class="btn btn-danger btn-sm active" role="button" aria-pressed="true">Hapus</a>
      <a href="{% url "perhitungan:edit" a.kodealternatif %}" class="btn btn-warning btn-sm active" role="button" aria-pressed="true">Edit</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="main" style="margin-left: 20px;">
<h4>TABLE NORMALISASI</h4>
</div>
<div class="d-flex justify-content-around">
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C1 NORMALISASI</th>
      </tr>
    </thead>
    <tbody>
      {% for a in normc1 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C2 NORMALISASI</th>
      </tr>
    </thead>
    <tbody>
      {% for a in normc2 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C3 NORMALISASI</th>
      </tr>
    </thead>
    <tbody>
      {% for a in normc3 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C4 NORMALISASI</th>
      </tr>
    </thead>
    <tbody>
      {% for a in normc4 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C5 NORMALISASI</th>
      </tr>
    </thead>
    <tbody>
      {% for a in normc5 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="main" style="margin-left: 20px;">
<h4>NORMALISASI X BOBOT</h4>
</div>
<div class="d-flex justify-content-around">

  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C1 X 25%</th>
      </tr>
    </thead>
    <tbody>
      {% for a in botc1 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C2 X 15%</th>
      </tr>
    </thead>
    <tbody>
      {% for a in botc2 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C3 X 30%</th>
      </tr>
    </thead>
    <tbody>
      {% for a in botc3 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C4 X 25%</th>
      </tr>
    </thead>
    <tbody>
      {% for a in botc4 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">C5 X 5%</th>
      </tr>
    </thead>
    <tbody>
      {% for a in botc5 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class="main" style="margin-left: 20px;">
  <h4>HASIL AKHIR</h4>
</div>
<div class="d-flex justify-content-around">

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">KODE ALTERNATIF</th>
    </tr>
  </thead>
  <tbody>
    {% for a in hasil %}
    <tr>
      <td>{{a}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">HASIL AKHIR</th>
      </tr>
    </thead>
    <tbody>
      {% for a in hasil2 %}
      <tr>
        <td>{{a}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock satu %}

templates/dasar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include "snippets/styles.html" %}
    {% block gaya %}
    
    {% endblock gaya%}
    <title>{{title}}</title>
</head>
<body>
{% include "snippets/nav.html" %}

{% block satu %}
{% endblock satu %}

{% include "snippets/script.html" %}
</body>
</html>

templates/index.html
{% extends 'dasar.html'%}

templates/snippets/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SPK-SAW</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "alternatif:index" %}">Alternatif</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url "perhitungan:index" %}">Perhitungan</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="">bobot</a>
      </li>
    </ul>
  </div>
</nav>

templates/snippets/script.html
{% load static %}
<script src="{% static "vendor\jquery\jquery.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "vendor\popper\popper.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "vendor\bootstrap\bootstrap.js" %}" type="text/javascript" charset="utf-8" async defer></script>
<script src="{% static "js\scrolling.js" %}" type="text/javascript" charset="utf-8" async defer></script>

templates/snippets/styles.html
{% load static%}
<link rel="stylesheet" href="{% static "vendor\bootstrap\bootstrap.css" %}">